echo Compiling LWUITDemo...
call ant clean build -file ../../Apps/LWUITDemo/LWUITDemoMIDP/build.xml
echo Compiling MIDP-SE...
call ant clean default -file ../MIDP_SE/build.xml
echo Compiling LWUIT UI...
call ant clean build -file ../../UI/build.xml
echo Compiling IO_SE...
call ant clean default -file ../../Ports/SE/IO_SE/build.xml
echo Installing LWUIT UI to maven repo...
call mvn install:install-file -Dfile=../../UI/dist/UI.jar -DgroupId=com.sun.lwuit -DartifactId=lwuit-ui-unmodified -Dversion=1.5 -Dpackaging=jar
echo Installing IO_SE to maven repo...
call mvn install:install-file -Dfile=../../Ports/SE/IO_SE/dist/IO_SE.jar -DgroupId=com.sun.lwuit.io -DartifactId=lwuit-io-se -Dversion=1.5 -Dpackaging=jar
echo Installing MIDP-SE to maven repo...
call mvn install:install-file -Dfile=../MIDP_SE/dist/MIDP_SE.jar -DgroupId=javax.microedition -DartifactId=midp-se -Dversion=1.0 -Dpackaging=jar
echo Installing LWUITDemo to maven repo...
call mvn install:install-file -Dfile=../../Apps/LWUITDemo/LWUITDemoMIDP/dist/LWUITDemo.jar -DgroupId=com.sun.lwuit.uidemo -DartifactId=lwuit-uidemo -Dversion=1.0 -Dpackaging=jar
echo Compiling swing-port...
call mvn clean install -f ../Lwuit-swingport/pom.xml
echo Compiling ResourceEditor
call mvn clean package



